- hosts: all
  become: true
  vars:
    mysql_root_pass: vagrant
    phpmyadmin_pass: vagrant
    phpmyadmin_host: mysql.lk
    nvm_user: vagrant
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
  tasks:
  - name: Update repository
    apt:
      update_cache: yes
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
  - name: Install essential tools
    apt: name={{ item }} state=present
    with_items:
      - git
      - vim
      - curl
      - wget
      - build-essential
      - gcc
      - make

  # Start of PPA
  # Add nginx stable repository from PPA and install its signing key.
  - name: Add nginx PPA
    apt_repository:
      repo: 'ppa:nginx/stable'
  - name: Add redis PPA
    apt_repository:
      repo: 'ppa:chris-lea/redis-server'
  - name: Add PHP PPA
    apt_repository:
      repo: 'ppa:ondrej/php'
  # End of PPA

  # Start of Installation
  - name: Install nginx
    apt:
      name: nginx
  - name: Install redis
    apt:
      name: redis-server
  # NOTE: the password problem
  # https://coderwall.com/p/sqdaya/mysql-server-installation-with-custom-password-in-ansible--2
  - name: Set MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_pass }}' vtype='password'
  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_pass }}' vtype='password'
  - name: Install MySQL
    apt: name={{ item }} state=present
    with_items:
      - mysql-server
      - mysql-client
  - name: Install PHP7
    apt: name={{ item }} state=present
    # TODO: enable error report
    with_items:
      - php7.1-fpm
      - php7.1-mcrypt
      - php7.1-zip
      - php7.1-redis
      - php7.1-xdebug
      - php7.1-curl
      - php7.1-gd
      - php7.1-intl
      - php7.1-mysql
      - php7.1-sqlite3
      - php7.1-xml
      - php7.1-mbstring
  - name: Set phpmyadmin webserver
    # TODO: how to skip this
    debconf: name='phpmyadmin' question='phpmyadmin/reconfigure-webserver' value='apache2' vtype='multiselect'
  - name: Set phpmyadmin dbconfig
    debconf: name='phpmyadmin' question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'
  - name: Set phpmyadmin mysql admin user
    debconf: name='phpmyadmin' question='phpmyadmin/mysql/admin-user' value='root' vtype='string'
  - name: Set phpmyadmin mysql admin user password
    debconf: name='phpmyadmin' question='phpmyadmin/mysql/admin-pass' value='{{ mysql_root_pass }}' vtype='password'
  - name: Set phpmyadmin admin user password
    debconf: name='phpmyadmin' question='phpmyadmin/mysql/app-pass' value='{{ phpmyadmin_pass }}' vtype='password'
  - name: Set phpmyadmin admin user password confirm
    debconf: name='phpmyadmin' question='phpmyadmin/app-password-confirm' value='{{ phpmyadmin_pass }}' vtype='password'
  - name: Install phpmyadmin
    apt:
      name: phpmyadmin
  - name: Update hosts for phpmyadmin
    lineinfile:
      dest: /etc/hosts
      # NOTE: must use double quote https://github.com/ansible/ansible/issues/4818
      line: "127.0.0.1\t{{ phpmyadmin_host }}"
  - name: Copy nginx config for phpmyadmin
    template:
      src: /vagrant/templates/phpmyadmin.j2
      dest: /etc/nginx/conf.d/phpmyadmin.conf
      owner: root
      group: root
      # TODO: file mode
    notify: restart nginx
  - name: Install nvm for user vagrant
    become_user: "{{ nvm_user }}"
    git: repo=https://github.com/creationix/nvm.git dest=~/.nvm
  - name: Export NVM_DIR
    become_user: "{{ nvm_user }}"
    lineinfile:
      dest: ~/.bashrc
      line: "export NVM_DIR=$HOME/.nvm"
      create: yes
  - name: Add nvm.sh to bashrc
    become_user: "{{ nvm_user }}"
    lineinfile:
      dest: ~/.bashrc
      line: "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"  # This loads nvm"
      create: yes
  - name: Install latest node LTS
    become_user: "{{ nvm_user }}"
    # Thanks to https://truongtx.me/2015/11/02/ansible-install-and-work-with-nodejs-using-nvm
    command: bash -c '. ~/.nvm/nvm.sh; nvm install lts/*; nvm alias default lts/*'
  # End of Installation

  # tasks:
  # - name: run this command and ignore the result
  #   shell: /usr/bin/somecommand
  #   ignore_errors: True
